# Prediction Model - LOB

Goal: predict `Lob Associata` (LOB) and evaluate whether the task can be automated.

Workflow:
1. Data checks (3 key questions)
2. Fast manual prefix analysis
3. Rule baseline (no ML)
4. ML baselines (Decision Tree, Naive Bayes, KNN)
5. Interpretable rules and automation/manual-review policy

## 1) Setup

In [30]:
import re
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, f1_score, classification_report, top_k_accuracy_score
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 220)

## 2) Load Data

In [31]:
NOTEBOOK_DIR = Path.cwd()
CANDIDATES = [
    NOTEBOOK_DIR / 'DB for DTM Project.xlsx',
    NOTEBOOK_DIR.parent / 'DB for DTM Project.xlsx',
]
FILE_PATH = next((p for p in CANDIDATES if p.exists()), None)
if FILE_PATH is None:
    raise FileNotFoundError('DB for DTM Project.xlsx not found in current or parent folder')

SHEET = 'Associazioni Cod. Art. - LOB'
df = pd.read_excel(FILE_PATH, sheet_name=SHEET)
df.columns = [str(c).strip() for c in df.columns]

print('File:', FILE_PATH)
print('Shape:', df.shape)
print('Columns:', list(df.columns))

df.head(3)

File: c:\Users\sveta\Documents\vem-product\DB for DTM Project.xlsx
Shape: (22655, 5)
Columns: ['Codice Articolo', 'Lob Associata', 'Nome LOB', 'Inventario', 'Descrizione Articolo']

        Codice Articolo  Lob Associata               Nome LOB  Inventario                               Descrizione Articolo
0                000050           1002  CABLAGGIO ALTERNATIVO  Inventario                    PATCH CORD UTP 2/RJ45 CAT5E MT2
1                000081           1002  CABLAGGIO ALTERNATIVO  Inventario              cab - cf54/150ez passerella a filo 3m
2  ‎000411AA230621QMANE           3004         CLOUD VARIE HW  Inventario  QUARKZMAN 30pz Ultra Sottile Telefono Leva Ape...

## 3) Define Core Columns

In [32]:
CODE_COL = 'Codice Articolo'
LOB_COL = 'Lob Associata'
LOB_NAME_COL = 'Nome LOB'
INV_COL = 'Inventario'
DESC_COL = 'Descrizione Articolo'

required = [CODE_COL, LOB_COL, INV_COL, DESC_COL]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f'Missing required columns: {missing}')

df_work = df[[c for c in [CODE_COL, LOB_COL, LOB_NAME_COL, INV_COL, DESC_COL] if c in df.columns]].copy()
for c in [CODE_COL, LOB_COL, INV_COL, DESC_COL]:
    df_work[c] = df_work[c].fillna('')

# Optional: apply cleaned LOB labels from data_quality output if available
DATA_QUALITY_DIR = NOTEBOOK_DIR / 'data_quality'
cleaned_target_path = DATA_QUALITY_DIR / 'associazioni_with_lob_cleaned.csv'

def _norm_lob(x):
    s = '' if pd.isna(x) else str(x).strip()
    if s.endswith('.0') and s[:-2].isdigit():
        s = s[:-2]
    return s

if cleaned_target_path.exists():
    clean_cols = [CODE_COL, 'Lob Associata Cleaned']
    df_clean = pd.read_csv(cleaned_target_path, usecols=[c for c in clean_cols if c in pd.read_csv(cleaned_target_path, nrows=0).columns])
    if CODE_COL in df_clean.columns and 'Lob Associata Cleaned' in df_clean.columns:
        df_clean['Lob Associata Cleaned'] = df_clean['Lob Associata Cleaned'].apply(_norm_lob)
        before = df_work[LOB_COL].astype(str).apply(_norm_lob)
        df_work = df_work.merge(df_clean[[CODE_COL, 'Lob Associata Cleaned']], on=CODE_COL, how='left')
        df_work[LOB_COL] = df_work['Lob Associata Cleaned'].fillna(df_work[LOB_COL]).astype(str).apply(_norm_lob)
        changed = int((before != df_work[LOB_COL]).sum())
        print(f'Applied cleaned LOB labels from {cleaned_target_path.name}: changed rows = {changed}')
    else:
        print('Cleaned target file found, but required columns are missing; using original LOB labels.')
else:
    print('Cleaned target file not found; using original LOB labels.')

print('Working shape:', df_work.shape)
df_work.head(3)

Applied cleaned LOB labels from associazioni_with_lob_cleaned.csv: changed rows = 53
Working shape: (22655, 6)

        Codice Articolo Lob Associata               Nome LOB  Inventario                               Descrizione Articolo Lob Associata Cleaned
0                000050          1002  CABLAGGIO ALTERNATIVO  Inventario                    PATCH CORD UTP 2/RJ45 CAT5E MT2                  1002
1                000081          1002  CABLAGGIO ALTERNATIVO  Inventario              cab - cf54/150ez passerella a filo 3m                  1002
2  ‎000411AA230621QMANE          3004         CLOUD VARIE HW  Inventario  QUARKZMAN 30pz Ultra Sottile Telefono Leva Ape...                  3004

## 4) Step 1 - Data Checks (3 Questions)

Q1. One codice -> always one LOB?

Q2. Are there clear code patterns?

Q3. Is there a relationship between LOB and Inventario?

In [33]:
# Q1: One codice -> one LOB?
code_lob_uniques = (
    df_work.groupby(CODE_COL)[LOB_COL]
    .nunique(dropna=True)
    .reset_index(name='lob_nunique')
)

ambiguous_codes = code_lob_uniques[code_lob_uniques['lob_nunique'] > 1].copy()

print('Unique codici:', len(code_lob_uniques))
print('Codici with >1 LOB:', len(ambiguous_codes))
print('Share ambiguous:', f"{len(ambiguous_codes)/len(code_lob_uniques):.2%}")

ambiguous_codes.head(20)

Unique codici: 22655
Codici with >1 LOB: 0
Share ambiguous: 0.00%

Empty DataFrame
Columns: [Codice Articolo, lob_nunique]
Index: []

In [34]:
# Helper prefix extractor for manual analysis
def extract_prefix(code: str, n: int = 5) -> str:
    text = str(code).upper().strip()
    text = re.sub(r'[^A-Z0-9]', '', text)
    if not text:
        return 'EMPTY'
    return text[:n]

df_work['prefix'] = df_work[CODE_COL].apply(extract_prefix)

# Q2: clear patterns in code prefixes?
prefix_lob = (
    df_work.groupby(['prefix', LOB_COL])
    .size()
    .reset_index(name='count')
    .sort_values('count', ascending=False)
)

prefix_stats = prefix_lob.copy()
prefix_stats['prefix_total'] = prefix_stats.groupby('prefix')['count'].transform('sum')
prefix_stats['confidence'] = prefix_stats['count'] / prefix_stats['prefix_total']

prefix_top = (
    prefix_stats.sort_values(['prefix', 'confidence', 'count'], ascending=[True, False, False])
    .drop_duplicates('prefix')
    .rename(columns={LOB_COL: 'dominant_lob', 'count': 'dominant_count'})
    .sort_values(['confidence', 'prefix_total'], ascending=False)
)

print('Prefixes:', prefix_top.shape[0])
print('Strong prefixes (support>=20 and confidence>=0.9):', int(((prefix_top['prefix_total'] >= 20) & (prefix_top['confidence'] >= 0.9)).sum()))

prefix_top.head(30)

Prefixes: 10125
Strong prefixes (support>=20 and confidence>=0.9): 43

      prefix dominant_lob  dominant_count  prefix_total  confidence
4317   CPAPS         6002             102           102         1.0
5405   FAS27         3014              43            43         1.0
2557   A1200         1006              36            36         1.0
2704   ACDC2        17001              33            33         1.0
4609   CVN07         1003              28            28         1.0
3130   ASA55         6001              27            27         1.0
4731   DG7GM         3002              27            27         1.0
4972   E3NMX         2016              27            27         1.0
9998   SWONT         3014              27            27         1.0
11100  WSC35         2002              26            26         1.0
483    11512         1002              25            25         1.0
10577  UTP28         1008              25            25         1.0
2803   AFFA2         3014              23            23         1.0
10578  UTP6A         1008              23            23         1.0
5363   F92EL         1008              22            22         1.0
8015   NWMSN         3005              22            22         1.0
5771   FZ2EL         1008              21            21         1.0
8034   NWSND         3005              21            21         1.0
10409  UCSCC         3009              21            21         1.0
2535   A0200         1006              20            20         1.0
4522   CSROO         4008              20            20         1.0
10178  TFSEC         6004              20            20         1.0
10449  UCSSP         3009              20            20         1.0
11102  WSC37         2002              20            20         1.0
2564   A1215         1006              19            19         1.0
2686   ACAC1        17001              19            19         1.0
3217   AUT00         6004              19            19         1.0
7947   NPC06         1001              19            19         1.0
3785   C9400         2002              18            18         1.0
9973   SWCOR         3014              18            18         1.0

In [35]:
# Q3: relationship LOB <-> Inventario
ct_count = pd.crosstab(df_work[LOB_COL], df_work[INV_COL])
ct_row_pct = pd.crosstab(df_work[LOB_COL], df_work[INV_COL], normalize='index').round(3)

print('LOB x Inventario (counts):')
display(ct_count.head(20))

print('LOB x Inventario (row percentages):')
display(ct_row_pct.head(20))

LOB x Inventario (counts):

Inventario     Assistenza  Inventario  Non in inventario
Lob Associata
1                       0           1                  0
1001                    0         498                  0
1002                    0        2014                  3
1003                    0        1068                 11
1006                    0         444                  0
1008                    0         418                  0
1011                    0          34                  0
1015                    0          44                  4
1016                    0          19                  0
12999                   0           1                  0
15007                   0           0                 71
15008                   0           0                 66
16999                   0           0                  1
17001                   0         911                 97
17005                   0         160                 19
17007                   0          10                 13
17008                   2           7                  7
17009                   0         166                  0
17999                   1           7                  0
19001                   0           0                 12

LOB x Inventario (row percentages):

Inventario     Assistenza  Inventario  Non in inventario
Lob Associata
1                   0.000       1.000              0.000
1001                0.000       1.000              0.000
1002                0.000       0.999              0.001
1003                0.000       0.990              0.010
1006                0.000       1.000              0.000
1008                0.000       1.000              0.000
1011                0.000       1.000              0.000
1015                0.000       0.917              0.083
1016                0.000       1.000              0.000
12999               0.000       1.000              0.000
15007               0.000       0.000              1.000
15008               0.000       0.000              1.000
16999               0.000       0.000              1.000
17001               0.000       0.904              0.096
17005               0.000       0.894              0.106
17007               0.000       0.435              0.565
17008               0.125       0.438              0.438
17009               0.000       1.000              0.000
17999               0.125       0.875              0.000
19001               0.000       0.000              1.000

## 5) Step 2 - Fast Manual Prefix Analysis

Simple table: `prefix -> dominant LOB` with support and confidence.

In [36]:
manual_prefix_table = prefix_top[['prefix', 'dominant_lob', 'prefix_total', 'dominant_count', 'confidence']].copy()
manual_prefix_table = manual_prefix_table.sort_values(['confidence', 'prefix_total'], ascending=False)

manual_prefix_table.head(50)

      prefix dominant_lob  prefix_total  dominant_count  confidence
4317   CPAPS         6002           102             102         1.0
5405   FAS27         3014            43              43         1.0
2557   A1200         1006            36              36         1.0
2704   ACDC2        17001            33              33         1.0
4609   CVN07         1003            28              28         1.0
3130   ASA55         6001            27              27         1.0
4731   DG7GM         3002            27              27         1.0
4972   E3NMX         2016            27              27         1.0
9998   SWONT         3014            27              27         1.0
11100  WSC35         2002            26              26         1.0
483    11512         1002            25              25         1.0
10577  UTP28         1008            25              25         1.0
2803   AFFA2         3014            23              23         1.0
10578  UTP6A         1008            23              23         1.0
5363   F92EL         1008            22              22         1.0
8015   NWMSN         3005            22              22         1.0
5771   FZ2EL         1008            21              21         1.0
8034   NWSND         3005            21              21         1.0
10409  UCSCC         3009            21              21         1.0
2535   A0200         1006            20              20         1.0
4522   CSROO         4008            20              20         1.0
10178  TFSEC         6004            20              20         1.0
10449  UCSSP         3009            20              20         1.0
11102  WSC37         2002            20              20         1.0
2564   A1215         1006            19              19         1.0
2686   ACAC1        17001            19              19         1.0
3217   AUT00         6004            19              19         1.0
7947   NPC06         1001            19              19         1.0
3785   C9400         2002            18              18         1.0
9973   SWCOR         3014            18              18         1.0
10428  UCSHD         3009            18              18         1.0
2050   76023         1001            17              17         1.0
4312   CPACT         6002            17              17         1.0
6379   IMPSM         4004            17              17         1.0
8914   QTE00         1003            17              17         1.0
10458  UCSXM         3009            17              17         1.0
2802   AFFA1         3014            16              16         1.0
3929   CBRCB         1002            16              16         1.0
9025   RCKAC         1006            16              16         1.0
488    11671         1001            15              15         1.0
2809   AFFC1         3014            15              15         1.0
4497   CSMIC         4008            15              15         1.0
4603   CVFG7         1003            15              15         1.0
8088   OCACC         1002            15              15         1.0
4848   DS224         3014            14              14         1.0
2558   A1204         1006            13              13         1.0
2661   AASSI         4008            13              13         1.0
2865   AIRCT         2001            13              13         1.0
4320   CPC33         1001            13              13         1.0
6926   LFPR2         6001            13              13         1.0

## 6) Step 3 - Rule Baseline (No ML)

Rule: `if prefix = X -> LOB = Y` (learned on train only).

In [37]:
rule_df = df_work[[CODE_COL, LOB_COL, 'prefix']].copy()
rule_df = rule_df[rule_df[LOB_COL].astype(str).str.strip() != '']

# Stratified split requires at least 2 samples per class.
lob_counts = rule_df[LOB_COL].value_counts()
rare_lobs = set(lob_counts[lob_counts < 2].index)

rule_df_model = rule_df[~rule_df[LOB_COL].isin(rare_lobs)].copy()
rule_df_rare = rule_df[rule_df[LOB_COL].isin(rare_lobs)].copy()

print('Total rows for rule baseline:', len(rule_df))
print('Rows excluded as rare LOB (<2 samples):', len(rule_df_rare))
print('Rare LOB classes excluded:', len(rare_lobs))

if rule_df_model[LOB_COL].nunique() < 2:
    raise ValueError('Not enough non-rare classes for stratified split in rule baseline.')

train_df, test_df = train_test_split(
    rule_df_model,
    test_size=0.2,
    random_state=42,
    stratify=rule_df_model[LOB_COL]
)

prefix_to_lob = (
    train_df.groupby('prefix')[LOB_COL]
    .agg(lambda s: s.value_counts().idxmax())
    .to_dict()
)

default_lob = train_df[LOB_COL].value_counts().idxmax()

test_pred_rule = test_df['prefix'].map(prefix_to_lob).fillna(default_lob)

rule_acc = accuracy_score(test_df[LOB_COL], test_pred_rule)
rule_f1_macro = f1_score(test_df[LOB_COL], test_pred_rule, average='macro')
rule_f1_weighted = f1_score(test_df[LOB_COL], test_pred_rule, average='weighted')

rule_metrics = pd.DataFrame([
    {'model': 'Prefix Rule Baseline', 'accuracy': rule_acc, 'f1_macro': rule_f1_macro, 'f1_weighted': rule_f1_weighted}
])
rule_metrics

Total rows for rule baseline: 22655
Rows excluded as rare LOB (<2 samples): 13
Rare LOB classes excluded: 13

                  model  accuracy  f1_macro  f1_weighted
0  Prefix Rule Baseline  0.556193  0.441478     0.576102

## 7) Step 4 - ML Baselines for LOB

Models:
- Decision Tree (mandatory)
- Naive Bayes (text-based)
- KNN (optional, included here)

In [38]:
ml_df = df_work[[CODE_COL, DESC_COL, INV_COL, LOB_COL, 'prefix']].copy()
ml_df = ml_df[ml_df[LOB_COL].astype(str).str.strip() != '']
ml_df[DESC_COL] = ml_df[DESC_COL].fillna('')

# Reuse rare classes from previous step if available; otherwise compute here.
if 'rare_lobs' not in globals():
    _counts = ml_df[LOB_COL].value_counts()
    rare_lobs = set(_counts[_counts < 2].index)

ml_df_model = ml_df[~ml_df[LOB_COL].isin(rare_lobs)].copy()

# Text features without target leakage
ml_df_model['input_text'] = (
    'CODE_' + ml_df_model[CODE_COL].astype(str) + ' ' +
    'PREFIX_' + ml_df_model['prefix'].astype(str) + ' ' +
    'INV_' + ml_df_model[INV_COL].astype(str) + ' ' +
    ml_df_model[DESC_COL].astype(str)
)

X = ml_df_model['input_text']
y = ml_df_model[LOB_COL].astype(str)

if y.nunique() < 2:
    raise ValueError('Not enough non-rare classes for ML modeling.')

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

vectorizer = CountVectorizer(lowercase=True, min_df=5, max_features=6000, ngram_range=(1,2), binary=True)
X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)
feature_names = vectorizer.get_feature_names_out()

print('Rows excluded as rare LOB (<2 samples):', len(ml_df) - len(ml_df_model))
print('Train shape:', X_train.shape)
print('Test shape:', X_test.shape)
print('Classes (after rare-class exclusion):', y.nunique())

Rows excluded as rare LOB (<2 samples): 13
Train shape: (18113, 6000)
Test shape: (4529, 6000)
Classes (after rare-class exclusion): 104

In [39]:
models = {
    'Decision Tree': DecisionTreeClassifier(
        random_state=42,
        max_depth=35,
        min_samples_leaf=5,
        class_weight='balanced'
    ),
    'Naive Bayes': MultinomialNB(alpha=0.5),
    'KNN': KNeighborsClassifier(
        n_neighbors=7,
        weights='distance',
        metric='cosine',
        algorithm='brute'
    )
}

results = []
trained_models = {}
predictions = {}
probabilities = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    proba = model.predict_proba(X_test)

    results.append({
        'model': name,
        'accuracy': accuracy_score(y_test, pred),
        'f1_macro': f1_score(y_test, pred, average='macro'),
        'f1_weighted': f1_score(y_test, pred, average='weighted')
    })

    trained_models[name] = model
    predictions[name] = pred
    probabilities[name] = proba

ml_metrics = pd.DataFrame(results).sort_values('f1_macro', ascending=False).reset_index(drop=True)

compare_df = pd.concat([rule_metrics, ml_metrics], ignore_index=True).sort_values('f1_macro', ascending=False).reset_index(drop=True)
compare_df

                  model  accuracy  f1_macro  f1_weighted
0                   KNN  0.649371  0.463693     0.644658
1  Prefix Rule Baseline  0.556193  0.441478     0.576102
2           Naive Bayes  0.654228  0.372531     0.634601
3         Decision Tree  0.177081  0.281057     0.186321

In [40]:
for name in ml_metrics['model']:
    print(f'\n===== {name} =====')
    print(classification_report(y_test, predictions[name], zero_division=0))

===== KNN =====
              precision    recall  f1-score   support

        1001       0.67      0.62      0.64       100
        1002       0.52      0.68      0.59       403
        1003       0.44      0.54      0.49       216
        1006       0.70      0.67      0.69        89
        1008       0.82      0.71      0.76        84
        1011       0.00      0.00      0.00         7
        1015       0.00      0.00      0.00        10
        1016       0.00      0.00      0.00         4
       15007       0.77      0.71      0.74        14
       15008       0.71      0.77      0.74        13
       17001       0.69      0.69      0.69       202
       17005       0.50      0.33      0.40        36
       17007       0.00      0.00      0.00         5
       17008       1.00      0.33      0.50         3
       17009       0.44      0.55      0.49        33
       17999       0.00      0.00      0.00         2
       19001       0.00      0.00      0.00         2
       20001       0.67      0.84      0.75        75
       20006       0.15      0.06      0.09        31
       20007       0.00      0.00      0.00         1
       20008       0.00      0.00      0.00         1
       20009       0.00      0.00      0.00         1
        2001       0.72      0.75      0.73       103
       20011       0.00      0.00      0.00         1
        2002       0.84      0.82      0.83       274
        2003       0.67      0.75      0.71        95
        2005       0.86      0.74      0.79        34
        2006       0.34      0.30      0.32        71
        2012       0.75      0.67      0.71         9
        2013       0.69      0.68      0.69        97
        2014       0.30      0.24      0.27        71
        2015       0.62      0.50      0.55        16
        2016       0.86      0.94      0.90        88
        2017       0.00      0.00      0.00         2
       24001       0.47      0.40      0.43       119
       24002       0.53      0.45      0.49        20
       24003       1.00      1.00      1.00         2
       25001       0.00      0.00      0.00         1
       25002       0.00      0.00      0.00         1
       26001       0.00      0.00      0.00         1
        2999       0.00      0.00      0.00         2
        3002       0.84      0.90      0.87        30
        3003       1.00      0.92      0.96        12
        3004       0.59      0.59      0.59       374
        3005       0.67      0.60      0.63        60
        3009       0.90      0.82      0.86       102
        3010       0.71      0.72      0.71        92
        3011       0.67      0.47      0.55        17
        3014       0.91      0.91      0.91       163
        3015       1.00      0.43      0.60         7
        3016       1.00      1.00      1.00         3
        3019       0.57      0.75      0.65        16
        3022       0.67      0.25      0.36         8
        3030       0.75      0.56      0.64        16
        3031       0.85      0.73      0.79        15
        3032       0.80      0.80      0.80        20
        3035       0.81      0.62      0.70        21
        3036       0.33      1.00      0.50         1
        3037       0.50      0.50      0.50         2
        3039       0.88      0.78      0.82         9
        3040       1.00      0.50      0.67         2
        3041       0.80      0.67      0.73         6
        3042       1.00      0.33      0.50         3
        3046       1.00      0.33      0.50         3
        3999       0.00      0.00      0.00         1
        4001       0.69      0.67      0.68        63
        4002       0.00      0.00      0.00        35
        4003       0.33      0.50      0.40         2
        4004       0.78      0.74      0.76        42
        4005       1.00      0.22      0.36         9
        4007       0.33      0.11      0.17        27
        4008       0.72      0.61      0.66        96
        4009       0.64      0.63      0.63       315
        4015       0.76      0.71      0.73        31
        4016       0.50      0.44      0.47         9
        4999       0.00      0.00      0.00         2
        5001       0.00      0.00      0.00         1
        6001       0.79      0.83      0.81        63
        6002       0.94      0.90      0.92       118
        6003       0.58      0.53      0.55        57
        6004       0.90      0.53      0.67        34
        6007       0.91      0.84      0.87        87
        6009       0.62      0.73      0.67        11
        6011       0.62      0.56      0.59        18
        6012       0.59      0.66      0.62        61
        6013       0.69      0.69      0.69        26
        6016       0.50      0.38      0.43         8
        6017       1.00      0.50      0.67         2
        6018       0.00      0.00      0.00         1
        6025       0.00      0.00      0.00         2
        6027       1.00      0.67      0.80         6
        6028       0.00      0.00      0.00         1
       99001       0.29      0.66      0.40        53
       99002       0.00      0.00      0.00         1
       99003       0.80      0.67      0.73         6
       99004       0.50      0.25      0.33         8
       99005       0.00      0.00      0.00         1
       99006       1.00      0.50      0.67         2
       99007       0.00      0.00      0.00         1
       99008       0.00      0.00      0.00         1
       99009       1.00      0.50      0.67         2
       99010       0.00      0.00      0.00         2
       99999       0.00      0.00      0.00         3

    accuracy                           0.65      4529
   macro avg       0.52      0.45      0.46      4529
weighted avg       0.65      0.65      0.64      4529


===== Naive Bayes =====
              precision    recall  f1-score   support

        1001       0.71      0.69      0.70       100
        1002       0.64      0.54      0.59       403
        1003       0.51      0.62      0.56       216
        1006       0.72      0.76      0.74        89
        1008       0.81      0.67      0.73        84
        1011       0.00      0.00      0.00         7
        1015       0.00      0.00      0.00        10
        1016       0.00      0.00      0.00         4
       15007       1.00      0.86      0.92        14
       15008       0.87      1.00      0.93        13
       17001       0.70      0.71      0.71       202
       17005       0.86      0.17      0.28        36
       17007       0.00      0.00      0.00         5
       17008       0.00      0.00      0.00         3
       17009       0.75      0.27      0.40        33
       17999       0.00      0.00      0.00         2
       19001       0.00      0.00      0.00         2
       20001       0.57      0.99      0.73        75
       20006       0.00      0.00      0.00        31
       20007       0.00      0.00      0.00         1
       20008       0.00      0.00      0.00         1
       20009       0.00      0.00      0.00         1
        2001       0.75      0.75      0.75       103
       20011       0.00      0.00      0.00         1
        2002       0.75      0.82      0.78       274
        2003       0.64      0.76      0.70        95
        2005       0.72      0.85      0.78        34
        2006       0.35      0.25      0.30        71
        2012       0.83      0.56      0.67         9
        2013       0.69      0.73      0.71        97
        2014       0.41      0.24      0.30        71
        2015       0.75      0.19      0.30        16
        2016       0.81      0.97      0.88        88
        2017       0.00      0.00      0.00         2
       24001       0.35      0.53      0.42       119
       24002       0.33      0.05      0.09        20
       24003       0.00      0.00      0.00         2
       25001       0.00      0.00      0.00         1
       25002       0.00      0.00      0.00         1
       26001       0.00      0.00      0.00         1
        2999       0.00      0.00      0.00         2
        3002       0.80      0.93      0.86        30
        3003       1.00      0.83      0.91        12
        3004       0.56      0.61      0.58       374
        3005       0.70      0.52      0.60        60
        3009       0.81      0.82      0.82       102
        3010       0.74      0.83      0.78        92
        3011       0.63      0.71      0.67        17
        3014       0.90      0.90      0.90       163
        3015       1.00      0.14      0.25         7
        3016       0.00      0.00      0.00         3
        3019       0.73      0.69      0.71        16
        3022       0.50      0.38      0.43         8
        3030       1.00      0.62      0.77        16
        3031       1.00      0.80      0.89        15
        3032       0.82      0.90      0.86        20
        3035       1.00      0.52      0.69        21
        3036       0.00      0.00      0.00         1
        3037       0.50      0.50      0.50         2
        3039       0.78      0.78      0.78         9
        3040       0.00      0.00      0.00         2
        3041       0.67      0.33      0.44         6
        3042       0.00      0.00      0.00         3
        3046       0.00      0.00      0.00         3
        3999       0.00      0.00      0.00         1
        4001       0.76      0.70      0.73        63
        4002       0.33      0.03      0.05        35
        4003       0.00      0.00      0.00         2
        4004       0.70      0.76      0.73        42
        4005       0.00      0.00      0.00         9
        4007       0.00      0.00      0.00        27
        4008       0.69      0.62      0.66        96
        4009       0.55      0.77      0.64       315
        4015       0.53      1.00      0.70        31
        4016       0.00      0.00      0.00         9
        4999       0.00      0.00      0.00         2
        5001       0.00      0.00      0.00         1
        6001       0.75      0.87      0.81        63
        6002       0.80      0.93      0.86       118
        6003       0.64      0.60      0.62        57
        6004       0.71      0.50      0.59        34
        6007       0.81      0.79      0.80        87
        6009       0.82      0.82      0.82        11
        6011       0.60      0.33      0.43        18
        6012       0.62      0.75      0.68        61
        6013       0.58      0.69      0.63        26
        6016       1.00      0.25      0.40         8
        6017       0.00      0.00      0.00         2
        6018       0.00      0.00      0.00         1
        6025       0.00      0.00      0.00         2
        6027       1.00      0.67      0.80         6
        6028       0.00      0.00      0.00         1
       99001       0.32      0.42      0.36        53
       99002       0.00      0.00      0.00         1
       99003       1.00      0.17      0.29         6
       99004       1.00      0.25      0.40         8
       99005       0.00      0.00      0.00         1
       99006       0.00      0.00      0.00         2
       99007       0.00      0.00      0.00         1
       99008       0.00      0.00      0.00         1
       99009       0.00      0.00      0.00         2
       99010       0.00      0.00      0.00         2
       99999       0.00      0.00      0.00         3

    accuracy                           0.65      4529
   macro avg       0.43      0.37      0.37      4529
weighted avg       0.64      0.65      0.63      4529


===== Decision Tree =====
              precision    recall  f1-score   support

        1001       0.00      0.00      0.00       100
        1002       0.00      0.00      0.00       403
        1003       0.25      0.00      0.01       216
        1006       0.03      1.00      0.05        89
        1008       0.00      0.00      0.00        84
        1011       0.00      0.00      0.00         7
        1015       0.09      0.30      0.14        10
        1016       0.00      0.00      0.00         4
       15007       0.91      0.71      0.80        14
       15008       1.00      0.85      0.92        13
       17001       0.00      0.00      0.00       202
       17005       0.00      0.00      0.00        36
       17007       0.00      0.00      0.00         5
       17008       0.00      0.00      0.00         3
       17009       0.00      0.00      0.00        33
       17999       0.00      0.00      0.00         2
       19001       0.00      0.00      0.00         2
       20001       0.76      0.69      0.73        75
       20006       0.48      0.48      0.48        31
       20007       0.25      1.00      0.40         1
       20008       0.00      0.00      0.00         1
       20009       0.00      0.00      0.00         1
        2001       0.87      0.46      0.60       103
       20011       0.00      0.00      0.00         1
        2002       0.75      0.01      0.02       274
        2003       0.67      0.02      0.04        95
        2005       0.87      0.38      0.53        34
        2006       0.00      0.00      0.00        71
        2012       0.50      0.22      0.31         9
        2013       1.00      0.11      0.20        97
        2014       0.00      0.00      0.00        71
        2015       0.00      0.00      0.00        16
        2016       0.84      0.95      0.89        88
        2017       0.40      1.00      0.57         2
       24001       0.00      0.00      0.00       119
       24002       0.00      0.00      0.00        20
       24003       0.00      0.00      0.00         2
       25001       0.20      1.00      0.33         1
       25002       0.00      0.00      0.00         1
       26001       0.00      0.00      0.00         1
        2999       0.00      0.00      0.00         2
        3002       1.00      0.10      0.18        30
        3003       1.00      0.50      0.67        12
        3004       0.00      0.00      0.00       374
        3005       0.90      0.32      0.47        60
        3009       1.00      0.60      0.75       102
        3010       0.83      0.75      0.79        92
        3011       0.67      0.47      0.55        17
        3014       0.75      0.02      0.04       163
        3015       0.67      0.57      0.62         7
        3016       0.50      1.00      0.67         3
        3019       0.56      0.31      0.40        16
        3022       0.71      0.62      0.67         8
        3030       1.00      0.56      0.72        16
        3031       0.75      0.60      0.67        15
        3032       0.75      0.45      0.56        20
        3035       0.92      0.52      0.67        21
        3036       0.33      1.00      0.50         1
        3037       0.67      1.00      0.80         2
        3039       0.75      0.33      0.46         9
        3040       0.50      0.50      0.50         2
        3041       1.00      0.33      0.50         6
        3042       1.00      0.67      0.80         3
        3046       0.50      0.33      0.40         3
        3999       0.00      0.00      0.00         1
        4001       0.82      0.52      0.64        63
        4002       0.00      0.00      0.00        35
        4003       0.00      0.00      0.00         2
        4004       0.33      0.02      0.04        42
        4005       0.38      0.33      0.35         9
        4007       0.00      0.00      0.00        27
        4008       1.00      0.02      0.04        96
        4009       1.00      0.00      0.01       315
        4015       0.71      0.55      0.62        31
        4016       0.26      0.67      0.38         9
        4999       0.00      0.00      0.00         2
        5001       0.00      0.00      0.00         1
        6001       1.00      0.02      0.03        63
        6002       1.00      0.10      0.18       118
        6003       0.81      0.60      0.69        57
        6004       0.80      0.12      0.21        34
        6007       1.00      0.34      0.51        87
        6009       0.67      0.73      0.70        11
        6011       0.42      0.28      0.33        18
        6012       0.74      0.48      0.58        61
        6013       0.80      0.46      0.59        26
        6016       0.15      0.50      0.24         8
        6017       0.40      1.00      0.57         2
        6018       0.00      0.00      0.00         1
        6025       0.00      0.00      0.00         2
        6027       1.00      0.67      0.80         6
        6028       0.00      0.00      0.00         1
       99001       0.00      0.00      0.00        53
       99002       0.00      0.00      0.00         1
       99003       1.00      0.17      0.29         6
       99004       0.02      0.75      0.04         8
       99005       0.00      0.00      0.00         1
       99006       0.00      0.00      0.00         2
       99007       0.00      0.00      0.00         1
       99008       0.20      1.00      0.33         1
       99009       1.00      1.00      1.00         2
       99010       1.00      0.50      0.67         2
       99012       0.00      0.00      0.00         0
       99999       0.00      0.00      0.00         3

    accuracy                           0.18      4529
   macro avg       0.41      0.30      0.28      4529
weighted avg       0.48      0.18      0.19      4529

## 8) Interpretable Patterns / Rules

### 8.1 Prefix Rules (human-readable)

In [41]:
interpretable_prefix_rules = manual_prefix_table[
    (manual_prefix_table['prefix_total'] >= 20) &
    (manual_prefix_table['confidence'] >= 0.90)
].copy()

interpretable_prefix_rules.head(100)

      prefix dominant_lob  prefix_total  dominant_count  confidence
4317   CPAPS         6002           102             102    1.000000
5405   FAS27         3014            43              43    1.000000
2557   A1200         1006            36              36    1.000000
2704   ACDC2        17001            33              33    1.000000
4609   CVN07         1003            28              28    1.000000
3130   ASA55         6001            27              27    1.000000
4731   DG7GM         3002            27              27    1.000000
4972   E3NMX         2016            27              27    1.000000
9998   SWONT         3014            27              27    1.000000
11100  WSC35         2002            26              26    1.000000
483    11512         1002            25              25    1.000000
10577  UTP28         1008            25              25    1.000000
2803   AFFA2         3014            23              23    1.000000
10578  UTP6A         1008            23              23    1.000000
5363   F92EL         1008            22              22    1.000000
8015   NWMSN         3005            22              22    1.000000
5771   FZ2EL         1008            21              21    1.000000
8034   NWSND         3005            21              21    1.000000
10409  UCSCC         3009            21              21    1.000000
2535   A0200         1006            20              20    1.000000
4522   CSROO         4008            20              20    1.000000
10178  TFSEC         6004            20              20    1.000000
10449  UCSSP         3009            20              20    1.000000
11102  WSC37         2002            20              20    1.000000
1705   56454         1002            97              96    0.989691
10419  UCSCP         3009            88              87    0.988636
11098  WSC29         2002            85              83    0.976471
2859   AIRCA         2001            36              35    0.972222
4310   CPACR         6002            32              31    0.968750
2851   AIRAN         2001            58              56    0.965517
4969   E3NMS         2016            29              28    0.965517
9176   S2636         3004            27              26    0.962963
2874   AIRPW         2001            25              24    0.960000
2866   AIRDN         2001            24              23    0.958333
5446   FC210         6007            22              21    0.954545
10438  UCSMR         3009            41              39    0.951220
4378   CPPWR         4001            20              19    0.950000
3790   C9500         2002            57              54    0.947368
10421  UCSCR         3009            34              32    0.941176
3644   C1000         2002            26              24    0.923077
7808   N9KC9         2002            23              21    0.913043
8823   PWRC1         2002            20              18    0.900000
8910   QSFPH         2002            20              18    0.900000

### 8.2 Decision Tree rules and top features

In [42]:
dt = trained_models['Decision Tree']

imp = pd.DataFrame({
    'feature': feature_names,
    'importance': dt.feature_importances_
}).sort_values('importance', ascending=False)

print('Top feature importances:')
display(imp.head(30))

print('\nDecision Tree rules (truncated):')
print(export_text(dt, feature_names=list(feature_names), max_depth=4))

Top feature importances:

                     feature  importance
4939                 red hat    0.025918
1533                  code_a    0.023700
5401                 startup    0.023305
1889               copertura    0.023096
3205        inventario cyber    0.022941
1738                 code_rs    0.022428
1709                code_pan    0.022398
3565                  meraki    0.021715
1473                  citrix    0.021259
1657                 code_hx    0.019028
5865                 vsphere    0.018582
2482              forcepoint    0.018400
3826                  normal    0.016669
1799                cohesity    0.016460
1022  application protection    0.016373
1104                     b21    0.015907
2701                 hitachi    0.015420
2781           in inventario    0.015213
830                       aa    0.014630
5636               trasporto    0.014182
7                        001    0.013968
3813                      nl    0.013887
270                      1yr    0.013748
5847                   voice    0.013360
5340                  spaces    0.012841
1967                  custom    0.012771
1586                 code_cp    0.012693
1585                code_con    0.012639
2122          dna essentials    0.012228
1553                  code_c    0.012178

Decision Tree rules (truncated):
|--- red hat <= 0.50
|   |--- code_a <= 0.50
|   |   |--- startup <= 0.50
|   |   |   |--- copertura <= 0.50
|   |   |   |   |--- inventario cyber <= 0.50
|   |   |   |   |   |--- truncated branch of depth 31
|   |   |   |   |--- inventario cyber >  0.50
|   |   |   |   |   |--- truncated branch of depth 9
|   |   |   |--- copertura >  0.50
|   |   |   |   |--- cisco <= 0.50
|   |   |   |   |   |--- class: 17009
|   |   |   |   |--- cisco >  0.50
|   |   |   |   |   |--- class: 99005
|   |   |--- startup >  0.50
|   |   |   |--- prefix_wstrt <= 0.50
|   |   |   |   |--- service <= 0.50
|   |   |   |   |   |--- class: 20011
|   |   |   |   |--- service >  0.50
|   |   |   |   |   |--- class: 99004
|   |   |   |--- prefix_wstrt >  0.50
|   |   |   |   |--- class: 17008
|   |--- code_a >  0.50
|   |   |--- premises <= 0.50
|   |   |   |--- smart <= 0.50
|   |   |   |   |--- meetings <= 0.50
|   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |--- meetings >  0.50
|   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |--- smart >  0.50
|   |   |   |   |--- class: 4016
|   |   |--- premises >  0.50
|   |   |   |--- ccx <= 0.50
|   |   |   |   |--- calling <= 0.50
|   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |--- calling >  0.50
|   |   |   |   |   |--- class: 4016
|   |   |   |--- ccx >  0.50
|   |   |   |   |--- class: 4016
|--- red hat >  0.50
|   |--- enterprise <= 0.50
|   |   |--- class: 3037
|   |--- enterprise >  0.50
|   |   |--- class: 3037

### 8.3 Naive Bayes class tokens

In [43]:
nb = trained_models['Naive Bayes']
nb_rows = []
for class_idx, cls in enumerate(nb.classes_):
    top_idx = np.argsort(nb.feature_log_prob_[class_idx])[::-1][:20]
    for rank, idx in enumerate(top_idx, start=1):
        nb_rows.append({
            'lob': cls,
            'rank': rank,
            'token': feature_names[idx],
            'log_prob': nb.feature_log_prob_[class_idx, idx]
        })

nb_tokens_df = pd.DataFrame(nb_rows)
nb_tokens_df

        lob  rank             token  log_prob
0      1001     1    inv_inventario -2.896764
1      1001     2              lszh -4.435955
2      1001     3               cat -4.521373
3      1001     4              rj45 -4.600885
4      1001     5               utp -4.798495
...     ...   ...               ...       ...
2075  99999    16                ev -7.633047
2076  99999    17               24v -7.633047
2077  99999    18              auto -7.633047
2078  99999    19  code_prestazione -7.633047
2079  99999    20                25 -7.633047

[2080 rows x 4 columns]

## 9) Automation vs Manual Review

In [44]:
best_model_name = ml_metrics.iloc[0]['model']
best_model = trained_models[best_model_name]
best_pred = predictions[best_model_name]
best_proba = probabilities[best_model_name]

max_proba = best_proba.max(axis=1)
conf_bucket = pd.cut(max_proba, bins=[-1, 0.65, 0.85, 1.0], labels=['low_manual_review', 'medium', 'high'])

policy_df = pd.DataFrame({
    'y_true': y_test.reset_index(drop=True),
    'y_pred': pd.Series(best_pred),
    'max_proba': max_proba,
    'bucket': conf_bucket
})
policy_df['correct'] = (policy_df['y_true'] == policy_df['y_pred']).astype(int)

bucket_summary = policy_df.groupby('bucket', observed=False).agg(
    n=('correct', 'size'),
    accuracy=('correct', 'mean')
).reset_index()
bucket_summary['share'] = bucket_summary['n'] / len(policy_df)

# Rule-based auto-cases
strong_prefixes = set(interpretable_prefix_rules['prefix']) if 'interpretable_prefix_rules' in globals() else set()
rule_auto_share = test_df['prefix'].isin(strong_prefixes).mean() if len(test_df) else 0.0

print('Best ML model:', best_model_name)
print('Share of strong prefix-rule cases in test:', f'{rule_auto_share:.2%}')

display(bucket_summary)

Best ML model: KNN
Share of strong prefix-rule cases in test: 7.02%

              bucket     n  accuracy     share
0  low_manual_review  2013  0.419771  0.444469
1             medium   758  0.726913  0.167366
2               high  1758  0.878840  0.388165

## 10) Final Conclusion Template

Fill from outputs above:
1. Can we automate LOB prediction?
2. Where is model/rule confidence high?
3. Where is manual review needed?

Suggested policy:
- Auto-assign when strong prefix rule exists OR ML confidence is high.
- Manual review for low-confidence and rare/ambiguous cases.

In [45]:
best = compare_df.iloc[0]
print('FINAL SUMMARY - LOB')
print(f"Best approach: {best['model']}")
print(f"Accuracy: {best['accuracy']:.4f}")
print(f"F1 macro: {best['f1_macro']:.4f}")
print(f"F1 weighted: {best['f1_weighted']:.4f}")
print(f"Rare LOB classes excluded from train/test: {len(rare_lobs)}")

if 'bucket_summary' in globals() and not bucket_summary.empty:
    high = bucket_summary[bucket_summary['bucket'] == 'high']
    low = bucket_summary[bucket_summary['bucket'] == 'low_manual_review']
    if len(high):
        print(f"High-confidence share: {high['share'].iloc[0]:.2%}, accuracy: {high['accuracy'].iloc[0]:.2%}")
    if len(low):
        print(f"Manual-review share (low confidence): {low['share'].iloc[0]:.2%}")

print('Use interpretable artifacts:')
print('- Prefix rules: interpretable_prefix_rules')
print('- Decision Tree rules: export_text output')
print('- Naive Bayes tokens: nb_tokens_df')

FINAL SUMMARY - LOB
Best approach: KNN
Accuracy: 0.6494
F1 macro: 0.4637
F1 weighted: 0.6447
Rare LOB classes excluded from train/test: 13
High-confidence share: 38.82%, accuracy: 87.88%
Manual-review share (low confidence): 44.45%
Use interpretable artifacts:
- Prefix rules: interpretable_prefix_rules
- Decision Tree rules: export_text output
- Naive Bayes tokens: nb_tokens_df

## 11) Hierarchical Baseline (Group -> Detailed LOB)

Two-stage prediction:
1. predict 2-digit LOB group,
2. predict detailed LOB inside predicted group.

In [46]:

def lob_group(code: str) -> str:
    s = str(code).strip()
    if s.endswith('.0') and s[:-2].isdigit():
        s = s[:-2]
    digits = ''.join(ch for ch in s if ch.isdigit())
    if not digits:
        return 'NA'
    return digits.zfill(2)[:2]

# Use same train/test split and vectorized matrices from ML baseline section
y_train_reset = y_train.reset_index(drop=True)
y_test_reset = y_test.reset_index(drop=True)
y_train_group = y_train_reset.astype(str).apply(lob_group)
y_test_group = y_test_reset.astype(str).apply(lob_group)

# Stage 1: group model
group_model = MultinomialNB(alpha=0.5)
group_model.fit(X_train, y_train_group)
group_pred = group_model.predict(X_test)

# Stage 2: one model per group for detailed class
group_detail_models = {}
global_default_lob = y_train_reset.value_counts().idxmax()

for g in sorted(y_train_group.unique()):
    idx = np.where(y_train_group.values == g)[0]
    y_sub = y_train_reset.iloc[idx]
    X_sub = X_train[idx]

    if y_sub.nunique() == 1:
        group_detail_models[g] = {'type': 'constant', 'label': y_sub.iloc[0]}
    else:
        m = MultinomialNB(alpha=0.5)
        m.fit(X_sub, y_sub)
        group_detail_models[g] = {'type': 'model', 'model': m}

# Predict detailed LOB
hier_pred = []
for i, g in enumerate(group_pred):
    info = group_detail_models.get(g)
    if info is None:
        hier_pred.append(global_default_lob)
    elif info['type'] == 'constant':
        hier_pred.append(info['label'])
    else:
        hier_pred.append(info['model'].predict(X_test[i])[0])

hier_acc = accuracy_score(y_test_reset, hier_pred)
hier_f1_macro = f1_score(y_test_reset, hier_pred, average='macro')
hier_f1_weighted = f1_score(y_test_reset, hier_pred, average='weighted')

hierarchical_metrics = pd.DataFrame([{
    'model': 'Hierarchical NB->NB',
    'accuracy': hier_acc,
    'f1_macro': hier_f1_macro,
    'f1_weighted': hier_f1_weighted
}])

hierarchical_metrics

                 model  accuracy  f1_macro  f1_weighted
0  Hierarchical NB->NB  0.638772   0.37155     0.619691

## 12) Hybrid Rule + ML Policy

Decision order:
1. strong prefix rule -> auto by rule,
2. else high-confidence ML -> auto by ML,
3. else -> manual review.

In [47]:

# Build rule stats on ML train split for fair combination
train_prefix = ml_df_model.loc[X_train_text.index, 'prefix'].astype(str).reset_index(drop=True)
test_prefix = ml_df_model.loc[X_test_text.index, 'prefix'].astype(str).reset_index(drop=True)

tmp_rule = pd.DataFrame({'prefix': train_prefix, 'lob': y_train_reset})
rule_support = tmp_rule.groupby('prefix').size().rename('support')
rule_top = tmp_rule.groupby('prefix')['lob'].agg(lambda s: s.value_counts().index[0]).rename('rule_lob')
rule_top_count = tmp_rule.groupby('prefix')['lob'].agg(lambda s: s.value_counts().iloc[0]).rename('top_count')

rule_table = pd.concat([rule_support, rule_top, rule_top_count], axis=1).reset_index()
rule_table['confidence'] = rule_table['top_count'] / rule_table['support']

rule_map = dict(zip(rule_table['prefix'], rule_table['rule_lob']))
rule_conf_map = dict(zip(rule_table['prefix'], rule_table['confidence']))
rule_support_map = dict(zip(rule_table['prefix'], rule_table['support']))

best_model_name = ml_metrics.iloc[0]['model']
best_pred = pd.Series(predictions[best_model_name]).reset_index(drop=True)
best_proba = probabilities[best_model_name]
best_classes = trained_models[best_model_name].classes_
max_proba = best_proba.max(axis=1)

rule_pred = test_prefix.map(rule_map)
rule_conf = test_prefix.map(rule_conf_map).fillna(0.0)
rule_sup = test_prefix.map(rule_support_map).fillna(0)

# Hybrid thresholds
RULE_MIN_SUPPORT = 20
RULE_MIN_CONF = 0.90
ML_MIN_CONF = 0.85

use_rule = rule_pred.notna() & (rule_sup >= RULE_MIN_SUPPORT) & (rule_conf >= RULE_MIN_CONF)
use_ml = (~use_rule) & (max_proba >= ML_MIN_CONF)

hybrid_decision = np.where(use_rule, 'auto_rule', np.where(use_ml, 'auto_ml', 'manual_review'))
hybrid_pred = np.where(use_rule, rule_pred, np.where(use_ml, best_pred, None))

hybrid_df = pd.DataFrame({
    'y_true': y_test_reset,
    'prefix': test_prefix,
    'rule_pred': rule_pred,
    'rule_conf': rule_conf,
    'rule_support': rule_sup,
    'ml_pred': best_pred,
    'ml_max_proba': max_proba,
    'decision': hybrid_decision,
    'hybrid_pred': hybrid_pred,
})

auto_mask = hybrid_df['decision'].isin(['auto_rule', 'auto_ml']) & hybrid_df['hybrid_pred'].notna()
manual_mask = hybrid_df['decision'] == 'manual_review'

auto_acc = accuracy_score(hybrid_df.loc[auto_mask, 'y_true'], hybrid_df.loc[auto_mask, 'hybrid_pred']) if auto_mask.any() else np.nan
auto_f1_macro = f1_score(hybrid_df.loc[auto_mask, 'y_true'], hybrid_df.loc[auto_mask, 'hybrid_pred'], average='macro') if auto_mask.any() else np.nan

# top-k quality for ML on full test
top3 = top_k_accuracy_score(y_test_reset, best_proba, k=3, labels=best_classes)
top5 = top_k_accuracy_score(y_test_reset, best_proba, k=5, labels=best_classes)

hybrid_summary = pd.DataFrame([
    {
        'best_ml_model': best_model_name,
        'rule_thresholds': f'support>={RULE_MIN_SUPPORT}, conf>={RULE_MIN_CONF}',
        'ml_threshold': ML_MIN_CONF,
        'auto_share': auto_mask.mean(),
        'manual_share': manual_mask.mean(),
        'auto_accuracy': auto_acc,
        'auto_f1_macro': auto_f1_macro,
        'ml_top3_acc': top3,
        'ml_top5_acc': top5,
    }
])

hybrid_summary

  best_ml_model         rule_thresholds  ml_threshold  auto_share  manual_share  auto_accuracy  auto_f1_macro  ml_top3_acc  ml_top5_acc
0           KNN  support>=20, conf>=0.9          0.85    0.393906      0.606094       0.878924       0.669748     0.814749     0.840804

## 13) Operational KPI Table (Auto Coverage / Manual Review / Top-3)

In [48]:

# Compare all approaches including hierarchical
all_compare = pd.concat([
    compare_df[['model', 'accuracy', 'f1_macro', 'f1_weighted']],
    hierarchical_metrics[['model', 'accuracy', 'f1_macro', 'f1_weighted']]
], ignore_index=True)

all_compare = all_compare.sort_values('f1_macro', ascending=False).reset_index(drop=True)
print('Model leaderboard (LOB):')
display(all_compare)

print('Hybrid policy KPI:')
display(hybrid_summary)

print('Decision split:')
display(hybrid_df['decision'].value_counts(dropna=False).rename_axis('decision').reset_index(name='count'))

Model leaderboard (LOB):

                  model  accuracy  f1_macro  f1_weighted
0                   KNN  0.649371  0.463693     0.644658
1  Prefix Rule Baseline  0.556193  0.441478     0.576102
2           Naive Bayes  0.654228  0.372531     0.634601
3   Hierarchical NB->NB  0.638772  0.371550     0.619691
4         Decision Tree  0.177081  0.281057     0.186321

Hybrid policy KPI:

  best_ml_model         rule_thresholds  ml_threshold  auto_share  manual_share  auto_accuracy  auto_f1_macro  ml_top3_acc  ml_top5_acc
0           KNN  support>=20, conf>=0.9          0.85    0.393906      0.606094       0.878924       0.669748     0.814749     0.840804

Decision split:

        decision  count
0  manual_review   2745
1        auto_ml   1574
2      auto_rule    210